// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhrchyrtdwtdtbwusfjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZocmNoeXJ0ZHd0ZHRid3VzZmp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNzQyODIsImV4cCI6MjA2NTg1MDI4Mn0.5CMQKv7p5tWU_MrPBseeXTh1who-wT4loPIU86BHL7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);